[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/en/index.html"
  status = 302

[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/ar"
  to = "/ar/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/error/error.html"
  status = 404