name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Scan JavaScript with ESLint
        run: |
          npm install eslint --save-dev
          npx eslint . --ext .js

      - name: Scan CSS with stylelint
        run: |
          npm install stylelint stylelint-config-standard --save-dev
          npx stylelint "**/*.css"

      - name: Scan HTML with htmlhint
        run: |
          npm install htmlhint --save-dev
          npx htmlhint "**/*.html"

  build-and-push:
    needs: scan-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/YOUR_IMAGE_NAME:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/YOUR_IMAGE_NAME:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/YOUR_IMAGE_NAME:latest